#!/usr/bin/env python3
import os
import zipfile
import html

def create_docx(filename, title, sections):
    content_types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>"""

    rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>"""

    doc_paragraphs = []
    # Title
    esc_title = html.escape(title)
    doc_paragraphs.append(f"""
    <w:p>
      <w:pPr><w:jc w:val="center"/><w:spacing w:after="300"/></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="48"/><w:color w:val="006699"/></w:rPr><w:t>{esc_title}</w:t></w:r>
    </w:p>
    <w:p>
      <w:pPr><w:jc w:val="center"/><w:spacing w:after="400"/></w:pPr>
      <w:r><w:rPr><w:i/><w:sz w:val="24"/><w:color w:val="555555"/></w:rPr><w:t>Simulation &amp; Management Prototype | Competition Submission</w:t></w:r>
    </w:p>
    """)

    for heading, paragraphs in sections:
        esc_h = html.escape(heading)
        doc_paragraphs.append(f"""
        <w:p>
          <w:pPr><w:spacing w:before="240" w:after="120"/></w:pPr>
          <w:r><w:rPr><w:b/><w:sz w:val="28"/><w:color w:val="003366"/></w:rPr><w:t>{esc_h}</w:t></w:r>
        </w:p>
        """)
        for p in paragraphs:
            esc_p = html.escape(p)
            doc_paragraphs.append(f"""
            <w:p>
              <w:pPr><w:spacing w:after="140"/><w:jc w:val="both"/></w:pPr>
              <w:r><w:rPr><w:sz w:val="22"/><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/></w:rPr><w:t xml:space="preserve">{esc_p}</w:t></w:r>
            </w:p>
            """)

    document_xml = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    {''.join(doc_paragraphs)}
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/>
    </w:sectPr>
  </w:body>
</w:document>"""

    os.makedirs(os.path.dirname(os.path.abspath(filename)), exist_ok=True)
    with zipfile.ZipFile(filename, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr('[Content_Types].xml', content_types)
        zf.writestr('_rels/.rels', rels)
        zf.writestr('word/document.xml', document_xml)

    print(f"Created docx document: {filename}")

if __name__ == "__main__":
    sections = [
        ("1. Core Concept & Genre", [
            "Data B-each: Island Eco-Resort is a single-player mobile simulation and management game built strictly in portrait orientation (9:16 aspect ratio). The player acts as the automated Overseer of an alien cyber-tropical getaway. The primary goal is achieving a 5-Star Resort rating and thriving economy while preventing power blackouts or ecological collapse within a focused 5-to-7 minute play session."
        ]),
        ("2. Core Loop Design & Interacting Systems", [
            "The game centers on a transparent, tightly coupled Invest -> Harvest -> Upgrade -> Optimize loop across three vital systems:",
            "• Databloons (Revenue): Earned from tourist-serving attractions (Beach Bars, Ramen Kiosks, Zero-G Surf Shacks, Luxury Villas).",
            "• Power Grid: Every attraction draws kilowatt load. Clean power is generated by Solar Canopies, Aero-Turbines, and Capacitor Banks. Insufficient power triggers brownouts, halving resort income and annoying guests.",
            "• Eco Cleanliness (Resort Health): High tourist volumes generate heat and cyber-debris. Maintained via Bio-Palm Groves, Algae Scrubbers, or manual tap-cleaning of beach waste. Falling below 30% causes guest evacuation.",
            "Upgrades increase revenue and capacity while demanding more power, forcing meaningful trade-offs with every purchase."
        ]),
        ("3. Session Escalation & Crisis Pacing", [
            "Because judges evaluate in a single sitting, the session escalates across four distinct phases: Sunrise Arrival (orientation), High Tide Rush (surging traffic), Signal Surge Storm (a high-voltage crisis causing solar fluctuations and demand spikes), and Neon Sunset Gala (peak capacity toward victory). The player wins by reaching 60,000 Databloons, a 4.8+ rating, and 75%+ Eco Health. Immediate one-tap retry is provided on failure."
        ]),
        ("4. Mobile Portrait Architecture & Technical Compliance", [
            "The layout adheres to modern mobile ergonomics: the upper two-thirds renders a 3D isometric Three.js diorama with visible building models, animated alien tourists, and floating feedback numbers. The lower third features a responsive thumb-reach drawer menu with tactile category tabs.",
            "The prototype is 100% self-contained and offline: all game code is formatted unminified in top-level index.html, local vendor libraries reside in vendor/, audio is synthesized dynamically with WebAudio, and the total zip package is under 2 MB (well below the 35 MB ceiling)."
        ])
    ]

    out_path = os.path.join(os.path.dirname(__file__), "..", "build", "design-intent.docx")
    create_docx(out_path, "Data B-each: Island Eco-Resort", sections)
